# thanks, chatgpt
name: Deploy Sushi Counter to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repository
      - name: Checkout
        uses: actions/checkout@v5

      # 2. Set up Node (npm comes with it)
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: 'npm'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build the site
      - name: Build
        run: npm run build

      # 5. Set up GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 6. Upload the dist folder
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

      # 7. Deploy
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
